name: 'billionaire_watcher'
version: '1.0.0'

profile: 'billionaire_watcher'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  billionaire_watcher:
    +materialized: table
    staging:
      +schema: staging
      +persist_docs:
        relation: true
        columns: true
      +contract:
        enforced: true
    intermediate:
      +schema: intermediate
      +persist_docs:
        relation: true
        columns: true
    marts:
      +schema: marts
      +persist_docs:
        relation: true
        columns: true

seeds:
  billionaire_watcher:
    dicionario:
      +enabled: true

vars:
  rf_partition_date: '2026-01-11'
  valor_1000_2025_publication_date: '2025-09-16'
