name: 'billionaire_watcher'
version: '1.0.0'

profile: 'billionaire_watcher'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  billionaire_watcher:
    +materialized: table
    staging:
      +schema: billionaire_watcher
      +materialized: table
      +meta:
        location: US
    freeze:
      +schema: billionaire_watcher
      +materialized: table
      +meta:
        location: US
    facts:
      +schema: billionaire_watcher
      +materialized: table
      +meta:
        location: US
    graph:
      +schema: billionaire_watcher
      +materialized: table
      +meta:
        location: US

seeds:
  billionaire_watcher:
    +schema: billionaire_watcher
    +meta:
      location: US

vars:
  rf_partition_date: '2026-01-11'
